name: Sandbox Workflow

on:
  workflow_dispatch:
    inputs:
      image-name:
        required: true
        type: string
      dockerfile-path:
        default: Dockerfile
        type: string
      failure-threshhold:
        default: error
        type: string

jobs:
  build:
    name: Docker Build job
    runs-on: ubuntu-latest
    environment: prd-build
    steps:
      - name: Starting Pipeline
        run: echo "Starting pipeline for ${{ inputs.image-name }}"
        shell: bash
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Hadolint on Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ inputs.dockerfile-path }}
          failure-threshold: ${{ inputs.failure-threshhold }}
      - name: Build image
        shell: bash
        run: |
          docker build -f ${{ inputs.dockerfile-path }} . -t ${{ inputs.image-name }}
          docker save ${{ inputs.image-name }} -o ${{ inputs.image-name }}.tar
      - name: Upload image as artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ inputs.image-name }}
          path: ${{ inputs.image-name }}.tar

  deploy:
    name: Docker Deploy job
    runs-on: ubuntu-latest
    needs: build
    environment: prd-deploy
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.image-name }}
      - name: Successfully Deployed
        run: echo "Successfully deployed ${{ inputs.image-name }}"
        shell: bash