name: Sandbox Workflow

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      dockerfile-path:
        default: Dockerfile
        type: string
      failure-threshhold:
        default: error
        type: string

jobs:
  build:
    name: Docker Build job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ inputs.dockerfile-path }}
          failure-threshold: ${{ inputs.failure-threshhold }}