name: Sandbox Workflow

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      dockerfile-path:
        default: Dockerfile
        type: string
      failure-threshhold:
        default: error
        type: string

jobs:
  build:
    name: Docker Build job
    runs-on: ubuntu-latest
    steps:
      - name: Starting Pipeline
        run: echo "Starting pipeline for ${{ inputs.image-name }}"
        shell: bash
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Hadolint on Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ inputs.dockerfile-path }}
          failure-threshold: ${{ inputs.failure-threshhold }}
      - name: Build image
        shell: bash
        run: docker build . -t ${{ inputs.image-name }}
            
